### ISSUE TITLE
[Enhancement]: Add NamespaceManager for handling Namespaces outside of the KubeResourceManager

### ISSUE THREAD

**Issue by im-konge** [skodjob/test-frame#119]
### Related problem

When we create a Namespace using KubeResourceManager, it is removed in the AfterAll/AfterEach test depending in which situation we are creating it. However, in some situations we want to skip the deletion of the Namespace and do it on completely different place. Or we want to do some clean-up before the Namespace is deleted. But because the steps are not done using `KubeResourceManager`, it will firstly delete everything from the stack and then it will continue with the steps from the AfterAll/Each.

### Suggested solution

Add NamespaceManager similarly to the one that is currently in the Strimzi test-suite: https://github.com/strimzi/strimzi-kafka-operator/blob/main/systemtest/src/main/java/io/strimzi/systemtest/resources/NamespaceManager.java

The main methods that should be implemented:

- for create and delete the Namespace(s)
- preparing the Namespace(s) - using some Runnable, Callback, whatever
- wait for Namespace(s) creation and deletion

### Alternatives

The alternative would be to implement it as part of the KubeResourceManager, however it can be a bit confusing.

**Comment by kornys** [comment]
won't do
