### ISSUE TITLE
Add new module for Strimzi related resources

### ISSUE THREAD

**Issue by im-konge** [skodjob/test-frame#14]

**Comment by kornys** [comment]
I can imagine that only in case that strimzi resources are used in other repositories. Like kafka or connectors etc...

**Comment by im-konge** [comment]
Yeah the initial idea was a bit different. But I also thought about it yesterday and I guess it can be an "extension" and, if needed, it can be kept in the particular org that will use it for everything else.

So I think we can close this as not planned.
