### ISSUE TITLE
Add MetricsCollector into test-frame

### ISSUE THREAD

**Issue by im-konge** [skodjob/test-frame#29]
In tests where we need to check metrics, it's useful to have some class that will take care of it. In Strimzi, we implemented [MetricsCollector](https://github.com/strimzi/strimzi-kafka-operator/blob/main/systemtest/src/main/java/io/strimzi/systemtest/metrics/MetricsCollector.java), which takes care of scraping these metrics and returning the Map<> with keys as name of Pods and values as the metrics from each Pod.

This can be useful for various projects, so having it in test-frame makes sense to me.

**Comment by see-quick** [comment]
This is good IMO.

For instance, when I was doing some work on the performance of UTO I had to create an additional class [1]. So with this, I would be able to simply add such dependency and then extend it in the separate repository if possible, which is good :). 

[1] - https://github.com/see-quick/strimzi-kafka-operator/commit/d17b1d07df85779781edee7b5efe8528618115df#diff-f41a3d24edf36fe98848585bfaf03afc1d450f0837b7c3ca582c835c3faf876f

**Comment by see-quick** [comment]
I will work on this ;) 🥇 If there are no objections.

**Comment by kornys** [comment]
cool, thx, look forward for PR.
